language: php
sudo: false

php:
  - 5.4

mysql:
  database: drupal
  username: root

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*@dev

  # Create the database.
  - "mysql -e 'create database drupal;'"
  - phpenv rehash

  # Build the distrobution.
  - bash scripts/setup
  - bash scripts/build.sh
  - cd /home/travis/build/DrupalHub/drupalhub/www

  # Install and migrate.
  - drush si -y drupalhub --account-name=admin --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal drupalhub_migrate_content.dummy_content=TRUE drupalhub_migrate_content.he_default_language=FALSE
  - drush mi --all --user=1

  # Minor setup.
  - drush vset drupalhub_files_available TRUE
  - drush vset drupalhub_push_notifications TRUE
  - drush cc all

  # Behat setup.
#  - cd profiles/drupalhub/behat
#  - cp behat.local.yml.travis behat.local.yml
#  - bin/behat --init

script:
  - echo 'hello!'
  # Run behat.
#  - bin/behat --tags=~wip

#after_script:
#  - cat ~/selenium.log