language: php
sudo: false

php:
  - 5.4

mysql:
  database: drupal
  username: root

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*@dev

  # Create the database.
  - "mysql -e 'create database drupal;'"
  - phpenv rehash

  # Build the distrobution.
  - bash scripts/setup
  - bash scripts/build.sh
  - cd /home/travis/build/DrupalHub/drupalhub/www

  # Add solr.
  - git clone https://github.com/RoySegall/solr-script.git
  - cd solr-script
  - bash solr.sh &
  - cd -

  # Install and migrate.
  - drush si -y drupalhub --account-name=admin --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal
  - drush mi --all --user=1

  # Minor setup.
  - drush vset drupalhub_push_notifications TRUE

  # Fire up the server
  - drush rs &

  # Running the front end.
  - cd ../design

  - bundle install
  - npm install
  - bower install

  # Run grnt
  - grunt travis > ~/grunt.log 2>&1 &

  - cd -

  # Run phatomJs
  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

  # Behat setup.
  - cd profiles/drupalhub/behat
  - cp behat.local.yml.travis behat.local.yml
  - composer install
  - bin/behat --init

script:
  # Run behat.
  - bin/behat --tags=~wip

#after_script:
#  - cat ~/selenium.log
