language: php
sudo: false

php:
  - 5.4

addons:
  apt:
    packages:
      - php5-cgi
      - php5-mysql
      - php5-curl

mysql:
  database: drupal
  username: root

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*@dev
 # Install phantom JS.
  - npm install -g phantomjs

before_script:

  # Create the database.
  - "mysql -e 'create database drupal;'"
  - phpenv rehash

  # Build the distrobution.
  - bash scripts/setup
  - bash scripts/build.sh
  - cd /home/travis/build/DrupalHub/drupalhub/www

  # Add solr.
  - git clone https://github.com/RoySegall/solr-script.git
  - cd solr-script
  - bash solr.sh &
  - cd -

  # Install and migrate.
  - drush si -y drupalhub --account-name=admin --account-pass=admin --db-url=mysql://root:@127.0.0.1/drupal
  - drush mi --all --user=1

  # Minor setup.
  - drush vset drupalhub_push_notifications TRUE

  # Fire up the server
  - drush rs > ~/rs.log 2>&1 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

  # Running the front end.
  - cd ../design

  - bundle install
  - npm install
  - bower install

  # Run grnt
  - grunt travis > ~/grunt.log 2>&1 &
  - until $(curl --output /dev/null --silent --head --fail http://0.0.0.0:9000; do sleep 1; echo '.'; done

  - cd -

  # Run phatomJs
  - phantomjs --webdriver=4444 > ~/phantomjs.log 2>&1 &

  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  # Behat setup.
  - cd profiles/drupalhub/behat
  - cp behat.local.yml.travis behat.local.yml
  - composer install
  - bin/behat --init

script:
  # Run behat.
  - bin/behat --tags=~wip

#after_script:
  - cat ~/grunt.log
  - cat ~/rs.log
