<?php
/**
 * @file
 * Code for the DrupalHub pages feature.
 */

include_once 'drupalhub_pages.features.inc';

/**
 * Implements hook_menu().
 */
function drupalhub_pages_menu() {
  $items = array();

  $items['drupalhub_pages/autocomplete'] = array(
    'title' => 'Node autocomplete',
    'page callback' => 'drupalhub_pages_autocomplete',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupalhub_pages_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_node_load().
 *
 * When which an idea we need to add a CSS. This is temporary until we have a
 * custom theme.
 */
function drupalhub_pages_node_load($nodes, $types) {
  if (!in_array('idea', $types)) {
    return;
  }

  drupal_add_css(drupal_get_path('module', 'drupalhub_pages') . '/css/drupalhub_pages.css');
}

/**
 * Return an array of tagged terms.
 */
function drupalhub_pages_tagged_terms() {
  // ti stands for taxonomy index.
  $query = db_select('taxonomy_index', 'ti');

  // td stands for taxonomy data.
  $query->join('taxonomy_term_data', 'td', 'td.tid = ti.tid');

  return $query
    ->fields('td', array('tid'))
    ->execute()
    ->fetchAllAssoc('tid');
}

/**
 * Get the number of tagged nodes per term.
 */
function drupalhub_pages_count_tagged_entities($tid) {
  $query = db_select('taxonomy_index', 'ti');
  return $query
    ->fields('ti', array('tid'))
    ->condition('ti.tid', $tid)
    ->execute()
    ->rowCount();
}

/**
 * usort callback function; Order the terms by the number of tagged items.
 */
function drupalhub_pages_order_terms($a, $b) {
  return $a['tagged'] > $b['tagged'] ? -1 : 1;
}

/**
 * Return list of nodes for the drupal of the month plugin.
 */
function drupalhub_pages_autocomplete($string = '') {
  $query = new EntityFieldQuery();
  $results = $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('title', '%' . $string . '%', 'LIKE')
    ->execute();

  if (empty($results['node'])) {
    return;
  }

  $nodes = node_load_multiple(array_keys($results['node']));

  foreach ($nodes as $node) {
    $data[$node->title . ' (' . $node->nid . ')'] = $node->title;
  }

  drupal_json_output($data);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function drupalhub_pages_form_views_exposed_form_alter(&$form, $form_state) {
  if ($form['#id'] != 'views-exposed-form-service-providers-panel-pane-1') {
    return;
  }

  $form['title']['#attributes']['placeholder'][] = t('Search for service provider');
}

