<?php
/**
 * @file
 * Code for the DrupalHub pages feature.
 */

include_once 'drupalhub_pages.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupalhub_pages_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_node_load().
 *
 * When which an idea we need to add a CSS. This is temporary until we have a
 * custom theme.
 */
function drupalhub_pages_node_load($nodes, $types) {
  if (!in_array('idea', $types)) {
    return;
  }

  drupal_add_css(drupal_get_path('module', 'drupalhub_pages') . '/css/drupalhub_pages.css');
}

/**
 * Return an array of tagged terms.
 */
function drupalhub_pages_tagged_terms() {
  // ti stands for taxonomy index.
  $query = db_select('taxonomy_index', 'ti');

  // td stands for taxonomy data.
  $query->join('taxonomy_term_data', 'td', 'td.tid = ti.tid');

  return $query
    ->fields('td', array('tid'))
    ->execute()
    ->fetchAllAssoc('tid');
}

/**
 * Get the number of tagged nodes per term.
 */
function drupalhub_pages_count_tagged_entities($tid) {
  $query = db_select('taxonomy_index', 'ti');
  return $query
    ->fields('ti', array('tid'))
    ->condition('ti.tid', $tid)
    ->execute()
    ->rowCount();
}

/**
 * usort callback function; Order the terms by the number of tagged items.
 */
function drupalhub_pages_order_terms($a, $b) {
  return $a['tagged'] > $b['tagged'] ? -1 : 1;
}
