<?php
/**
 * @file
 * Mail module file for DrupalHub social.
 */

/**
 * Twitter local consumer key
 */
define('TWITTER_KEY', '31u5KDR3gHY6LwaXuiRg');

/**
 * Twitter local consumer secret
 */
define('TWITTER_SECRET', 'xKZPt7AeiMki3ul4qTAJbkQEv90IVqYW1tiDEAWtuU');

/**
 * Facebook app ID.
 */
define('FACEBOOK_ID', '197114067137623');

/**
 * Facebook secret.
 */
define('FACEBOOK_SECRET', '5413a965a5332ba5bf411eb48a814f27');

/**
 * Github ID.
 */
define('GITHUB_ID', 'fa43e37f80ff324af010');

/**
 * Github secret
 */
define('GITHUB_SECRET', '3aebce3c7902bd954c19eb55647cf2329744aa21');

/**
 * Implements hook_form_FORM_ID_alter().
 */
function drupalhub_social_form_alter(&$form, $form_state, $form_id) {
  if ($form_id != 'user_login') {
    return;
  }

 $form['#after_build'][] = 'drupalhub_social_set_buttons';
}

/**
 * Adding to the button of the twitter the other social networks the user can
 * logged in with.
*/
function drupalhub_social_set_buttons($form, $form_state) {
  global $base_url;

  // Using twitter connect API for create the login button with custom design.
  $form['twitter_signin'] = array(
    '#markup' => l('<div class="social-icon twitter"><i class="fa fa-twitter"></i></div>', 'twitter/redirect', array('html' => TRUE)),
  );

  // Using facebook connect API for create the login button with custom design.
  $app_id = isset($app_id) ? $app_id : variable_get('fboauth_id', '');
  $link = fboauth_action_link_properties('connect', NULL, $app_id);

  $form['facebook_signin'] = array(
    '#markup' => l('<div class="social-icon facebook"><i class="fa fa-facebook"></i></div>', $link['href'], array('html' => TRUE, 'query' => $link['query'])),
  );

  // Using github connect API for create the login button with custom design.
  $client_id = variable_get('github_connect_client_id');
  $destination = user_login_destination();
  $link =
    'https://github.com/login/oauth/authorize?client_id=' . $client_id .
    '&scope=user,public&redirect_uri=' .
    urlencode($base_url . '/github/register/create?destination=' . $destination['destination']);

  $output = l('<div class="social-icon github"><i class="fa fa-github"></i></div>', $link, array('html' => TRUE,));

  $form['github_signin'] = array(
    '#markup' => $output,
  );

  return $form;
}
