<?php
/**
 * @file
 * Code for the drupalhub_users feature.
 */

include_once 'drupalhub_users.features.inc';

/**
 * Implements hook_account_created().
 */
function drupalhub_users_user_insert(&$edit, $account, $category) {
  $message = message_create('new_user', array('uid' => $account->uid));
  $message->save();
}


/**
 * Get the user picture.
 *
 * @param $user
 *   The user object.
 *
 * @return string
 *   HTML of the user picture.
 */
function drupalhub_users_user_picture($user) {

  if ($user->picture) {
    return file_create_url($user->picture->uri);
  }

  if ($image = _gravatar_get_account_user_picture($user)) {
    return $image;
  }

  return file_create_url(file_load(variable_get('default_user_picture_fid'))->uri);
}
