<?php
/**
 * @file
 * Code for the DrupalHub Videos feature.
 */

include_once 'drupalhub_videos.features.inc';

/**
 * Get metadata for a youtube video by a given ID.
 *
 * @param $id
 *   The youtube video ID.
 *
 * @return Array
 *   Array with metadata about the video.
 */
function drupalhub_videos_get_metadata($id) {
  $cache_id = 'youtube_metadata_' . $id;

  if ($cache = cache_get($cache_id)) {
    return $cache->data;
  }

  $information = drupal_http_request('http://gdata.youtube.com/feeds/api/videos/' . $id . '?v=2&alt=jsonc');

  // No information. Return early.
  if ($information->code != 200) {
    return;
  }

  $request = drupal_json_decode($information->data);

  cache_set($cache_id, $request['data'], 'cache');

  return $request['data'];
}

/**
 *  Implements hook_permission().
 */
function drupalhub_videos_permission() {
  return array(
    'suggested videos approved' => array(
      'title' => t('Suggested videos approved'),
      'description' => t('Will approve youtube videos when sending them.')
    ),
  );
}

/**
 * Implements hook_node_presave().
 */
function drupalhub_videos_node_presave($node) {

  if ($node->type != 'youtube') {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $node);

  $value = $wrapper->field_address->value();

  $id = _video_embed_field_get_youtube_id($value['video_url']);
  $data = drupal_http_request('https://www.googleapis.com/youtube/v3/videos?id=' . $id . '&key=AIzaSyB9GaMYWcFitmreglsphxlBIm1WO5IXUeM&part=snippet,contentDetails,statistics,status');
  $video_info = drupal_json_decode($data->data);
  $video_info = $video_info['items'][0];

  $value['video_data'] = serialize(array(
    'handler' => 'youtube',
    'duration' => $video_info['contentDetails']['duration'],
    'channel_title' => $video_info['snippet']['channelTitle'],
    'channel_id' => $video_info['snippet']['channelId'],
    'stats' => $video_info['statistics'],
  ));

  $wrapper->field_address->set($value);
}
