<?php
/**
 * @file
 * Code for the DrupalHub Videos feature.
 */

include_once 'drupalhub_videos.features.inc';

/**
 * Get metadata for a youtube video by a given ID.
 *
 * @param $id
 *   The youtube video ID.
 *
 * @return Array
 *   Array with metadata about the video.
 */
function drupalhub_videos_get_metadata($id) {
  $cache_id = 'youtube_metadata_' . $id;

  if ($cache = cache_get($cache_id)) {
    return $cache->data;
  }

  $information = drupal_http_request('http://gdata.youtube.com/feeds/api/videos/' . $id . '?v=2&alt=jsonc');

  // No information. Return early.
  if ($information->code != 200) {
    return;
  }

  $request = drupal_json_decode($information->data);

  cache_set($cache_id, $request['data'], 'cache');

  return $request['data'];
}

/**
 *  Implements hook_permission().
 */
function drupalhub_videos_permission() {
  return array(
    'suggested videos approved' => array(
      'title' => t('Suggested videos approved'),
      'description' => t('Will approve youtube videos when sending them.')
    ),
  );
}
