<?php
/**
 * @file
 * Code for the Drupalhub Group feature.
 */

include_once 'drupalhub_group.features.inc';

/**
 * Get list of service providers.
 *
 * @return stdClass[];
 */
function drupalhub_group_get_service_providers() {
  $query = new EntityFieldQuery();
  $results = $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'drupalhub_group')
    ->execute();

  if (empty($results['node'])) {
    return;
  }

  return node_load_multiple(array_keys($results['node']));
}

/**
 *  Implements hook_preprocess_HOOK().
 */
function drupalhub_group_preprocess_page(&$variables) {

  if (!module_exists('og_context')) {
    return;
  }

  if (!$context = og_context()) {
    return;
  }

  $wrapper = entity_metadata_wrapper('node', $context['gid']);
  $image = $wrapper->field_group_logo->value();

  $variables['site_name'] = $wrapper->label();
  $variables['logo'] = file_create_url($image['uri']);
}