<?php
/**
 * @file
 * Code for the drupalhub_questions feature.
 */

include_once 'drupalhub_questions.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupalhub_questions_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
  if ($module == 'restful') {
    return "plugins/$plugin";
  }
}

function drupalhub_questions_field_formatter_info() {
  return array(
    'drupalhub_questions' => array( //Machine name of the formatter
      'label' => t('DrupalHub questions'),
      'field types' => array('vud'), //This will only be available to text fields
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function drupalhub_questions_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $wrapper = entity_metadata_wrapper($entity_type, $entity);

  if ($entity_type != 'node') {
    return;
  }

  if ($wrapper->getBundle() != 'question') {
    return;
  }

  $votes = new VoteUpDown($entity_type, $entity);

  $value = 0;

  foreach ($votes->getVotes() as $vote) {
    $value += $vote->value;
  }

  $element[0]['#markup'] = $value;

  return $element;
}

/**
 *  Implements hook_preprocess_HOOK().
 */
function drupalhub_questions_preprocess_html(&$variables) {
  $menu = menu_get_item();
  if ($menu['path'] != "node/%") {
    return;
  }

  $node = $menu['map'][1];

  if ($node->type != 'question') {
    return;
  }

  drupalhub_core_ckeditor_add_assets('question');
  ctools_add_js('inline_edit', 'drupalhub_questions');
  drupal_add_js(libraries_get_path('dialog') . '/dist/js/bootstrap-dialog.min.js');
  drupal_add_js(array('drupalhub_question' => array(
    'nid' => $node->nid,
    'access' => node_access('update', $node),
  )), array('type' => 'setting'));
  $variables['attributes_array'] = array('data-ng-app' => array('QuestionApp'), 'data-ng-controller' => array('TitleController'));
}
