<?php

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Authorization, access_token,Content-Type, permission');
header('Access-Control-Allow-Methods: *');

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupalhub_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return "plugins/$plugin";
  }
  if ($module == 'entity_validator') {
    return 'plugins/' . $plugin;
  }
}
