<?php

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true');
header('Access-Control-Allow-Headers: Authorization, access_token,Content-Type, permission');
header('Access-Control-Allow-Methods: *');

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupalhub_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return "plugins/$plugin";
  }
  if ($module == 'entity_validator') {
    return 'plugins/' . $plugin;
  }
}


/**
 * Implements hook_entity_property_info_alter().
 */
function drupalhub_restful_entity_property_info_alter(&$info) {
  $info['user']['bundles']['user']['properties']['pass'] = array(
    'label' => t('Password'),
    'setter callback' => 'drupalhub_restful_set_user_pass',
    'schema field' => 'pass',
  );

  $info['user']['properties']['name']['getter callback'] = 'drupalhub_restful_get_user_name';
}

/**
 * Setter callback; Set user password.
 */
function drupalhub_restful_set_user_pass($account, $name, $value) {
  require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
  $account->pass = user_hash_password($value);
}

function drupalhub_restful_get_user_name($account, $name, $value) {
  return empty($account->name) ? variable_get('anonymous', t('Anonymous')) : $account->name;
}
