<?php
/**
 * @file
 * Code for the DrupalHub search feature.
 */

include_once 'drupalhub_search.features.inc';

/**
 *  Implements hook_search_api_index_items_alter().
 */
function drupalhub_search_search_api_index_items_alter(array &$items, SearchApiIndex $index) {
  if ($index->getEntityType() != 'node') {
    return;
  }

  foreach ($items as $delta => $item) {
    $wrapper = entity_metadata_wrapper('node', $item);

    if ($wrapper->getBundle() != 'youtube') {
      continue;
    }

    if (!$wrapper->field_show_in_videos->value()) {
      unset($items[$delta]);
    }
  }
}