<?php
/**
 * @file
 * Main module for for DrupalHub migrate.
 */

/**
 * Implements hook_migrate_api().
 */
function drupalhub_migrate_migrate_api() {

  $classes = array(
    'User',
    'Blog',
    'Group',
    'Project',
    'Youtube',
    'Comment',
    'Category',
    'Question',
    'GroupBanner',
    'Recommendation',
  );

  $api = array(
    'api' => 2,
    'migrations' => array(),
  );

  foreach ($classes as $class) {
    $api['migrations'][$class] = array('class_name' => $class);
  }

  return $api;
}
