<?php

/**
 * @file
 * Code for the DrupalHub WIKI module.
 */

include_once 'drupalhub_wiki.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupalhub_wiki_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return "plugins/$plugin";
  }
}

/**
 * The form of the search box.
 */
function drupalhub_wiki_search_form($form, $form_state) {
  $form['text'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#attributes' => array(
      'placeholder' => array(t('Enter text')),
    ),
  );

  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Search!'),
    ),
  );
  return $form;
}
