<?php

/**
 * @file
 * Code for the DrupalHub WIKI module.
 */

include_once 'drupalhub_wiki.features.inc';

/**
 * Implements hook_menu().
 */
function drupalhub_wiki_menu_alter(&$items) {
  $items['documentation/add'] = array(
    'page callback' => 'drupalhub_wiki_add_node',
  ) + $items['node/add/wiki'];
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function drupalhub_wiki_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return "plugins/$plugin";
  }
}

/**
 * The form of the search box.
 */
function drupalhub_wiki_search_form($form, $form_state) {
  $form['text'] = array(
    '#type' => 'textfield',
    '#title' => '',
    '#attributes' => array(
      'placeholder' => array(t('Enter text')),
    ),
  );

  $form['actions'] = array(
    '#type' => 'actions',
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Search!'),
    ),
  );
  return $form;
}

/**
 * DrupalHub Wikipedia links.
 */
function drupalhub_wiki_links() {
  $items = array(
    l(t('Front page'), 'documentation'),
    l(t('FAQ'), 'documentation/FAQ'),
    l(t('Top rated'), 'documentation/top-rated'),
    l(t('Most viewed'), 'documentation/most-viewed'),
  );

  if (user_access('create wiki content')) {
    $items[] = l(t('Create documentation'), 'documentation/add');
  }

  return "<div class='wikipedia-tabs'>" . theme('item_list', array('items' => $items)) . '</div>';
}

/**
 * Create wiki node callback.
 */
function drupalhub_wiki_add_node() {
  $content = '';

  $content .= drupalhub_wiki_links();

  global $user;
  $type = 'wiki';
  $node = (object) array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => $type, 'language' => LANGUAGE_NONE);
  $form = drupal_get_form($type . '_node_form', $node);
  hide($form['body'][LANGUAGE_NONE][0]['format']);
  $content .= render($form);

  return $content;
}
